export const logos: any = {
  'ACURA': 'acura',
  'AGRALE': 'agrale',
  'ALFA ROMEO': 'alfaromeo',
  'ASIA MOTORS': 'asia',
  'ASTON MARTIN': 'aston',
  'AUDI': 'audi',
  'BAIC': 'baic',
  'BABY': 'baby',
  'BRM': 'brm',
  'BMW': 'bmw',
  'BUGRE': 'bugre',
  'CADILLAC': 'cadillac',
  'CBT JIPE': 'cbt',
  'CHANA': 'chana',
  'CHANGAN': 'changan',
  'CHERY': 'chery',
  'CHEVROLET': 'chevrolet',
  'CHRYSLER': 'chrysler',
  'CITROËN': 'citroen',
  'CROSS LANDER': 'crosslander',
  'DAEWOO': 'daewoo',
  'DAIHATSU': 'daihatsu',
  'DFM': 'dfm',
  'DFSK': 'dfsk',
  'DODGE': 'dodge',
  'GM - Chevrolet': 'chevrolet',
  'DS AUTOMOBILES': 'dsautomobiles',
  'EFFA': 'effa',
  'ENGESA': 'engesa',
  'ENVEMO': 'envemo',
  'FERRARI': 'ferrari',
  'FIAT': 'fiat',
  'FIBRAVAN': 'fibravan',
  'FYBER': 'fyber',
  'FORD': 'ford',
  'FORD CAMION': 'ford',
  'FOTON': 'foton',
  'GEELY': 'geely',
  'GREAT WALL': 'greatwall',
  'GURGEL': 'gurgel',
  'HAFEI': 'hafei',
  'HAVAL': 'haval',
  'HITECH ELECTRIC': 'hitech',
  'HINO': 'hino',
  'HONDA': 'honda',
  'HUMMER': 'img/logos/ico-hummer',
  'HYUNDAI': 'hyundai',
  'ISUZU': 'isuzu',
  'IVECO': 'iveco',
  'JAC': 'jac',
  'JAGUAR': 'jaguar',
  'JEEP': 'jeep',
  'JINBEI': 'jinbei',
  'JMC': 'jmc',
  'JPX': 'jpx',
  'KIA MOTORS': 'kia',
  'LADA': 'lada',
  'LAMBORGHINI': 'lamborghini',
  'LAND ROVER': 'landrover',
  'LEXUS': 'lexus',
  'LIFAN': 'lifan',
  'LOBINI': 'lobini',
  'LOTUS': 'lotus',
  'MACK': 'mack',
  'MAHINDRA': 'Mahindra',
  'MATRA': 'matra',
  'MASERATI': 'maserati',
  'MAZDA': 'mazda',
  'MCLAREN': 'mclaren',
  'MERCEDES-BENZ': 'mercedesBenz',
  'MERCEDES BENZ C': 'mercedesBenz',
  'MERCURY': 'mercuri',
  'MG': 'mg',
  'MINI': 'minicooper',
  'MITSUBISHI': 'mitsubishi',
  'NISSAN': 'nissan',
  'PEUGEOT': 'peugeot',
  'PLYMOUTH': 'plymouth',
  'PONTIAC': 'pontiac',
  'PORSCHE': 'porsche',
  'RAM': 'ram',
  'RELY': 'rely',
  'RENAULT': 'renault',
  'RENAULT CAMION': 'renault',
  'ROLLS-ROYCE': 'rollsroyce',
  'ROVER': 'rover',
  'SAAB': 'saab',
  'SATURN': 'saturn',
  'SCANIA': 'scania',
  'SEAT': 'seat',
  'SHINERAY': 'shineray',
  'SMART': 'smart',
  'SSANGYONG': 'ssangyong',
  'SUBARU': 'subaru',
  'SUZUKI': 'suzuki',
  'TAC': 'tac',
  'TATA': 'tata',
  'TOYOTA': 'toyota',
  'TROLLER': 'troller',
  'VOLKSWAGEN': 'volkswagen',
  'VOLKSWAGEN CAM.': 'volkswagen',
  'VOLVO': 'volvo',
  'VOLVO CAMION': 'volvo',
  'WAKE': 'wake',
};
