export const logos = {
  'ACURA': '../images/logos/ico-acura.svg',
  'AGRALE': '../images/logos/ico-agrale.svg',
  'ALFA ROMEO': '../images/logos/ico-alfaromeo.svg',
  'ASIA MOTORS': '../images/logos/ico-asia.svg',
  'ASTON MARTIN': '../images/logos/ico-aston.svg',
  'AUDI': '../images/logos/ico-audi.svg',
  'BAIC': '../images/logos/ico-baic.svg',
  'BABY': '../images/logos/ico-baby.svg',
  'BRM': '../images/logos/ico-brm.svg',
  'BMW': '../images/logos/ico-bmw.svg',
  'BUGRE': '../images/logos/ico-bugre.svg',
  'CADILLAC': '../images/logos/ico-cadillac.svg',
  'CBT JIPE': '../images/logos/ico-cbt.svg',
  'CHANA': '../images/logos/ico-chana.svg',
  'CHANGAN': '../images/logos/ico-changan.svg',
  'CHERY': '../images/logos/ico-chery.svg',
  'CHEVROLET': '../images/logos/ico-chevrolet.svg',
  'CHRYSLER': '../images/logos/ico-chrysler.svg',
  'CITROEN': '../images/logos/ico-citroen.svg',
  'CROSS LANDER': '../images/logos/ico-crosslander.svg',
  'DAEWOO': '../images/logos/ico-daewoo.svg',
  'DAIHATSU': '../images/logos/ico-daihatsu.svg',
  'DFM': '../images/logos/ico-dfm.svg',
  'DFSK': '../images/logos/ico-dfsk.svg',
  'DODGE': '../images/logos/ico-dodge.svg',
  'DS AUTOMOBILES': '../images/logos/ico-dsautomobiles.svg',
  'EFFA': '../images/logos/ico-effa.svg',
  'ENGESA': '../images/logos/ico-engesa.svg',
  'ENVEMO': '../images/logos/ico-envemo.svg',
  'FERRARI': '../images/logos/ico-ferrari.svg',
  'FIAT': '../images/logos/ico-fiat.svg',
  'FIBRAVAN': '../images/logos/ico-fibravan.svg',
  'FYBER': '../images/logos/ico-fyber.svg',
  'FORD': '../images/logos/ico-ford.svg',
  'FORD CAMION': '../images/logos/ico-ford.svg',
  'FOTON': '../images/logos/ico-foton.svg',
  'GEELY': '../images/logos/ico-geely.svg',
  'GREAT WALL': '../images/logos/ico-greatwall.svg',
  'GURGEL': '../images/logos/ico-gurgel.svg',
  'HAFEI': '../images/logos/ico-hafei.svg',
  'HAVAL': '../images/logos/ico-haval.svg',
  'HITECH ELECTRIC': '../images/logos/ico-hitech.svg',
  'HINO': '../images/logos/ico-hino.svg',
  'HONDA': '../images/logos/ico-honda.svg',
  'HUMMER': 'img/logos/ico-hummer.svg',
  'HYUNDAI': '../images/logos/ico-hyundai.svg',
  'ISUZU': '../images/logos/ico-isuzu.svg',
  'IVECO': '../images/logos/ico-iveco.svg',
  'JAC': '../images/logos/ico-jac.svg',
  'JAGUAR': '../images/logos/ico-jaguar.svg',
  'JEEP': '../images/logos/ico-jeep.svg',
  'JINBEI': '../images/logos/ico-jinbei.svg',
  'JMC': '../images/logos/ico-jmc.svg',
  'JPX': '../images/logos/ico-jpx.svg',
  'KIA MOTORS': '../images/logos/ico-kia.svg',
  'LADA': '../images/logos/ico-lada.svg',
  'LAMBORGHINI': '../images/logos/ico-lamborghini.svg',
  'LAND ROVER': '../images/logos/ico-landrover.svg',
  'LEXUS': '../images/logos/ico-lexus.svg',
  'LIFAN': '../images/logos/ico-lifan.svg',
  'LOBINI': '../images/logos/ico-lobini.svg',
  'LOTUS': '../images/logos/ico-lotus.svg',
  'MACK': '../images/logos/ico-mack.svg',
  'MAHINDRA': '../images/logos/ico-Mahindra.svg',
  'MATRA': '../images/logos/ico-matra.svg',
  'MASERATI': '../images/logos/ico-maserati.svg',
  'MAZDA': '../images/logos/ico-mazda.svg',
  'MCLAREN': '../images/logos/ico-mclaren.svg',
  'MERCEDES-BENZ': '../images/logos/ico-mercedesBenz.svg',
  'MERCEDES BENZ C': '../images/logos/ico-mercedesBenz.svg',
  'MERCURY': '../images/logos/ico-mercuri.svg',
  'MG': '../images/logos/ico-mg.svg',
  'MINI': '../images/logos/ico-minicooper.svg',
  'MITSUBISHI': '../images/logos/ico-mitsubishi.svg',
  'NISSAN': '../images/logos/ico-nissan.svg',
  'PEUGEOT': '../images/logos/ico-peugeot.svg',
  'PLYMOUTH': '../images/logos/ico-plymouth.svg',
  'PONTIAC': '../images/logos/ico-pontiac.svg',
  'PORSCHE': '../images/logos/ico-porsche.svg',
  'RAM': '../images/logos/ico-ram.svg',
  'RELY': '../images/logos/ico-rely.svg',
  'RENAULT': '../images/logos/ico-renault.svg',
  'RENAULT CAMION': '../images/logos/ico-renault.svg',
  'ROLLS-ROYCE': '../images/logos/ico-rollsroyce.svg',
  'ROVER': '../images/logos/ico-rover.svg',
  'SAAB': '../images/logos/ico-saab.svg',
  'SATURN': '../images/logos/ico-saturn.svg',
  'SCANIA': '../images/logos/ico-scania.svg',
  'SEAT': '../images/logos/ico-seat.svg',
  'SHINERAY': '../images/logos/ico-shineray.svg',
  'SMART': '../images/logos/ico-smart.svg',
  'SSANGYONG': '../images/logos/ico-ssangyong.svg',
  'SUBARU': '../images/logos/ico-subaru.svg',
  'SUZUKI': '../images/logos/ico-suzuki.svg',
  'TAC': '../images/logos/ico-tac.svg',
  'TATA': '../images/logos/ico-tata.svg',
  'TOYOTA': '../images/logos/ico-toyota.svg',
  'TROLLER': '../images/logos/ico-troller.svg',
  'VOLKSWAGEN': '../images/logos/ico-volkswagen.svg',
  'VOLKSWAGEN CAM.': '../images/logos/ico-volkswagen.svg',
  'VOLVO': '../images/logos/ico-volvo.svg',
  'VOLVO CAMION': '../images/logos/ico-volvo.svg',
  'WAKE': '../images/logos/ico-wake.svg',
};
